version: '3.7'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: trading_container
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
      POSTGRES_DB: tradingdb
    networks:
      quarkus-net:
        ipv4_address: 172.30.0.2

  # PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: trading@trading.com # Set your admin email
      PGADMIN_DEFAULT_PASSWORD: trading          # Set your admin password
    ports:
      - "5050:80"
    networks:
      quarkus-net:
        ipv4_address: 172.30.0.3
    depends_on:
      - postgres

  # Kafka Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      quarkus-net:
        ipv4_address: 172.30.0.4

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      quarkus-net:
        ipv4_address: 172.30.0.5
    depends_on:
      - zookeeper


networks:
  quarkus-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
